export const plans = [
  {
    id: 'starter',
    name: 'Starter',
    price: 0,
    period: '7-day trial',
    analyses: '5 analyses',
    features: ['Full AI analysis', 'Expert Panel', 'Basic dashboard'],
    cta: 'Start Free Trial',
    popular: false,
  },
  {
    id: 'lite',
    name: 'Lite',
    price: 0,
    period: 'forever',
    analyses: '1 analysis/month',
    features: ['Keep your data', 'Health Score & Streak', 'Read-only past reports'],
    cta: 'Free – No Credit Card',
    popular: false,
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 79,
    period: 'month',
    analyses: 'Unlimited analyses',
    features: ['Full analytics suite', 'Expert Panel', 'What‑If Simulator', 'Excel AI', 'Community access', 'Export to PDF/Excel'],
    cta: 'Subscribe Now',
    popular: true,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 299,
    period: 'month',
    analyses: '300 analyses/month',
    features: ['Everything in Pro', 'Team management', 'SSO & RBAC', 'Audit logs', 'Competitor intelligence', 'White‑label'],
    cta: 'Contact Sales',
    popular: false,
  },
  {
    id: 'enterprise-plus',
    name: 'Enterprise+',
    price: 2499,
    period: 'month',
    analyses: 'Unlimited analyses',
    features: ['Everything in Enterprise', 'Dedicated cloud deployment', 'Custom AI fine‑tuning', 'Named CSM', 'Code escrow included'],
    cta: 'Contact Sales',
    popular: false,
  },
];

export const getPlan = (id: string) => plans.find(p => p.id === id);
